main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, \
    BBPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate, send_email, \
    DeleteUserViews, by_rubric, detail, profile_bb_add, profile_bb_delete, profile_bb_change

app_name = 'main'
urlpatterns = [
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('mail/', send_email),
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/delete/', DeleteUserViews.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

online_board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))  # Отключение кэшировани
                                                                        # статических файлов

main/forms.py
from .models import AdvUser, SubRubric, SuperRubric, Bb, AdditionalImage, Comment
from captcha.fields import  CaptchaField
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory


# Формы для работы с разграничениям доступа
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адресс электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адресс электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Введите тот же пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают',
                                                   code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False

        if commit:
            user.save()

        # user_registrated.send(RegisterUserForm, instance=user)

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


# Формы для работы с рубриками
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.object.all(),
                                          empty_label=None,
                                          label='Надрубрика',
                                          required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


# Форма для поиска на сайте
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=40, label='')


# Форма для работы с объявлениями
class BbForm(forms.ModelForm):
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


# Форма для добавления комментариев
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('as_active',)
        widgets = {'bb': forms.HiddenInput}

    captcha = CaptchaField(label='Введите код с картинки',
                           error_messages={'invalid': 'Неправильный текст'})

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.db.models import Q

from .models import AdvUser, SubRubric, Bb, Comment
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, BbForm, AIFormSet, CommentForm
from .utilities import signer
from django.core.mail import send_mail


# Главная страница
def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)


# Контроллер для обработки страниц которые выводят информацию которую не нужно обрабатывать или доставать из БД
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')  # Формирование и поиск шаблона
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required()  # Декоратор (показывает страницу если пользователь авторизирован)
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


@login_required()
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request,
                                     messages.SUCCESS,
                                     'Объявление добавлено')

                return redirect('main:profile')

    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()

    context = {'form': form, 'formset': formset}

    return render(request, 'main/profile_bb_add.html', context)


@login_required()
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request,
                                     messages.SUCCESS,
                                     'Объявление исправленно')

                return redirect('main:profile')

    else:
        form = BbForm(instance=bb)
        formset = AIFormSet()

    context = {'bb': bb, 'form': form, 'formset': formset}

    return render(request, 'main/profile_bb_change.html', context)


@login_required()
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request,
                             messages.SUCCESS,
                             'Объявлени успешно удалено')

        return redirect('main:profile')

    else:
        context = {'bb': bb}

        return render(request, 'main/profile_bb_delete.html', context)


class BBLogoutView(LoginRequiredMixin, LogoutView):  #LoginRequireMixin это для того чтобы он был доступен только
                                                     # для зарегистрированых
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin,
                         LoginRequiredMixin,
                         UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info_view.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователей изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin,
                           LoginRequiredMixin,
                           PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


# Контроллер активации пользователя
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')

    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


def send_email(request):
    send_mail(
        'Subject here',
        'Here is the message.',
        'yatsuranikitatest@gmail.com',
        ['nikitayatsuraprograming@gmail.com'],
        fail_silently=False,
    )
    return HttpResponse('nice')


class DeleteUserViews(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontails=keyword) | Q(content__icontiles=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''

    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form}

    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):
    bb = Bb.objects.get(pk=pk)
    ais = bb.additionalimage_set.all()  # Дополнительные илюстрации
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}

    if request.user.is_authenticated:
        initial['author'] = request.user.username

    form_class = CommentForm
    form = form_class(initial=initial)

    if request.method == 'POST':
        c_form = form_class(request.POST)

        if c_form.is_valid():
            c_form.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request,
                                 messages.WARNING,
                                 'Комментарий не добавлен')

    context = {'bb': bb, 'ais': ais, 'comments': comments, 'form': form}

    return render(request, 'main/detail.html', context)

templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %} О сайте {% endblock %}

{% block content %}
    <h2>О сайте</h2>
    <p>Сайт для публикации объявлений о продаже</p>
    <p>Все права пренадлежат читателям книги &quot;Django 2.1&quot;</p>
{% endblock %}

templates/main/bad_signature.html
{% extends 'layout/basic.html' %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>При активации пользователя произошла ошибка</p>
    <p><a href="{% url 'main:register' %}"></a>Зарегистрироваться повторно</p>
{% endblock %}

templates/main/by_rubric.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
    <h2 class="mb-2">{{ rubric }}</h2>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
            <form action="" class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %}
                {% bootstrap_button content='Искать' button_type='submit' %}
            </form>
        </div>
    </div>
    {% if bbs %}
        <ul class="list-unstyled">
            {% for bb in bbs %}
                <li class="media my-5 p-3 border">
                    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                            <img src="/{% thumbnail bb.image 'default' %}" alt="" class="mr-3">
                        {% else %}
                            <img src="{% static 'media/main/empty.jpg' %}" alt="" class="mr-3">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <div class="">{{ bb.content }}</div>
                        <p class="text-right font-weight-bold">{{ bb.price }}</p>
                        <p class="text-right font-italic">{{ bb.create_at }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% bootstrap_pagination page url=keyword %}
    {% endif %}
{% endblock %}

templates/main/change_user_info_view.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}

    <h2>Правка личных данных пользователя {{ user.user_name }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сохранить' %}{% endbuttons %}
    </form>

{% endblock %}

templates/main/index.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
    <h2 class="mb-2">{{ rubric }}</h2>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
{#            <form action="" class="col-md-auto form-inline">#}
{#                {% bootstrap_form form show_label=False %}#}
{#                {% bootstrap_button content='Искать' button_type='submit' %}#}
{#            </form>#}
        </div>
    </div>
    {% if bbs %}
        <ul class="list-unstyled">
            {% for bb in bbs %}
                <li class="media my-5 p-3 border">
                    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                            <img src="/{% thumbnail bb.image 'default' %}" alt="" class="mr-3">
                        {% else %}
                            <img src="{% static 'media/main/empty.jpg' %}" alt="" class="mr-3">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <div class="">{{ bb.content }}</div>
                        <p class="text-right font-weight-bold">{{ bb.price }}</p>
                        <p class="text-right font-italic">{{ bb.create_at }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
{#        {% bootstrap_pagination page url=keyword %}#}
    {% endif %}
{% endblock %}

templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}

    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход</p>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="next" value="{{ next }}">
            {% buttons submit='Войти' %}{% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

templates/main/logout.html
{% extends 'layout/basic.html' %}

{% block title %}Выход{% endblock %}

{% block content %}

    <h2>Выход</h2>
    <p>Вы успешно вышли с сайта</p>

{% endblock %}

templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    <h2>Смена пароля пользователя {{ user.user_name }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сменить пароль' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}</p>
    {% else %}
        <p>Здравствуйте</p>
    {% endif %}
    <p><a href="{% url 'main:profile_bb_add' %}">Добавить новое объявление</a></p>
    <h3>Ваши объявления</h3>
    {% for bb in bbs %}
        <div class="media-body">
            <p>Рубрика: {{ bb.rubric }}</p>
            <h3><a href="{% url 'main:detail' rubric_pk=bb.rubric.pk pk=bb.pk %}{{ all }}">{{ bb.title }}</a></h3>
            <div class="">{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }}</p>
            <p class="text-right font-italic">{{ bb.create_at }}</p>
            <p><a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Редактировать</a></p>
            <p><a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a></p>
        </div>
    {% endfor %}
{% endblock %}

templates/main/profile_bb_add.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Добавления объявления - Профиль пользователя{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_formset formset layout='horizontal' %}
        {% buttons submit='Добавить' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/profile_bb_delete.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
    <h2>Удаление объявления {{ bb.title }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% buttons submit='Удалить' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация пользователя завершена.</p>
    <p>На вашей электронной почте, указаной при регистрации, выслано письмо для активации</p>
{% endblock %}

templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/user_is_activated.html
{% extends 'layout/basic.html' %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь уже был активирован</p>
    <p><a href="{% url 'main:login' %}"></a>Войти на сайт</p>
{% endblock %}