main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, \
    BBPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate, send_email, \
    DeleteUserViews, by_rubric, detail, profile_bb_add, profile_bb_delete, profile_bb_change

app_name = 'main'
urlpatterns = [
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('mail/', send_email),
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/delete/', DeleteUserViews.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

online_board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))  # Отключение кэшировани
                                                                        # статических файлов

templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Главная {% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'layout/basic.css' %}">
    {% block style %}

    {% endblock %}
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text_center">Объявления</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a href="{% url 'main:register' %}" class="nav-link">Регистрация</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                aria-expanded="false">Профиль</a>
                <div class="dropdown-menu">
                    <a href="{% url 'main:profile' %}" class="dropdown-item">Мои объявления</a>
                    <a href="{% url 'main:profile_change' %}" class="dropdown-item">Изменить личные данные</a>
                    <a href="{% url 'main:password_change' %}" class="dropdown-item">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'main:logout' %}" class="dropdown-item">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'main:profile_delete' %}" class="dropdown-item">Удалить</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a href="{% url 'main:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a href="{% url 'main:index' %}" class="nav-link root">Главная</a>
            {% for rubric in rubrics %}
                {% ifchanged rubric.super_rubric.pk %}
                <span class="nav-link root font-weight-bold">{{rubric.super_rubric.name}}</span>
                {% endifchanged %}
                <a href="{% url 'main:by_rubric' pk=rubric.pk %}" class="nav-link">{{rubric.name}}</a>
            {% endfor %}
            <a href="{% url 'main:other' page='about' %}" class="nav-link root">О сайте</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; Доска объявлений</p>
    </footer>
</body>
</html>